import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Product, request } from "./api";
import { ProductAutocomplete } from "./ProductAutocomplete";

type ProductPlus = Product & { sku: string; token_enabled?: boolean; token_value?: string;minimum_stock: number };
type Stock = { product_id: string; sku: string; name: string; packaging: string; quantity: string; value: string; minimum_stock: string; is_low_stock: boolean };
type Movement = { id: string; product_id: string; movement_type: string; quantity: string; unit_cost: string; occurred_on: string; reference_type?: string; notes?: string };
const pkr = (value: string | number) => new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", maximumFractionDigits: 0 }).format(Number(value));

export function InventoryViewV2() {
  const client = useQueryClient();
  const [productId, setProductId] = useState("");
  const [quantity, setQuantity] = useState(0);
  const [notes, setNotes] = useState("");
  const stock = useQuery({ queryKey: ["stock"], queryFn: () => request<Stock[]>("/inventory/stock") });
  const products = useQuery({ queryKey: ["products"], queryFn: () => request<ProductPlus[]>("/products?limit=200") });
  const movements = useQuery({ queryKey: ["stock-movements"], queryFn: () => request<Movement[]>("/inventory/movements?limit=200") });
  const adjustment = useMutation({ mutationFn: () => request("/inventory/adjustments", { method: "POST", body: JSON.stringify({ product_id: productId, quantity, notes }) }), onSuccess: () => { setProductId(""); setQuantity(0); setNotes(""); client.invalidateQueries({ queryKey: ["stock"] }); client.invalidateQueries({ queryKey: ["stock-movements"] }); client.invalidateQueries({ queryKey: ["dashboard"] }); } });
  const submit = (event: FormEvent) => { event.preventDefault(); adjustment.mutate(); };
  return <section className="invoice-page"><h1>Inventory</h1><ProductCreatePanel /><section className="panel"><h2>Stock adjustment</h2><form className="line-adder" onSubmit={submit}><select required value={productId} onChange={e => setProductId(e.target.value)}><option value="">Select product</option>{products.data?.map(product => <option key={product.id} value={product.id}>{product.sku} — {product.name}</option>)}</select><input required type="number" step="0.001" placeholder="+/- quantity" value={quantity || ""} onChange={e => setQuantity(Number(e.target.value))} /><input required placeholder="Reason / notes" value={notes} onChange={e => setNotes(e.target.value)} /><button disabled={adjustment.isPending}>Post adjustment</button></form>{adjustment.error && <p className="error">{adjustment.error.message}</p>}</section><section className="panel"><h2>Current stock</h2><table><thead><tr><th>SKU</th><th>Product</th><th>Quantity</th><th>Value</th><th>Token</th><th>Status</th></tr></thead><tbody>{stock.data?.map(item => { const product = products.data?.find(p => p.id === item.product_id); return <tr key={item.product_id}><td>{item.sku}</td><td>{item.name}</td><td>{item.quantity}</td><td>{pkr(item.value)}</td><td>{product?.token_enabled ? "Token bearing" : "No token"}</td><td>{item.is_low_stock ? "Low stock" : "OK"}</td></tr>; })}</tbody></table></section><section className="panel"><h2>Movement history</h2><table><thead><tr><th>Date</th><th>Type</th><th>Product</th><th>Quantity</th><th>Unit cost</th><th>Reference</th></tr></thead><tbody>{movements.data?.map(m => <tr key={m.id}><td>{m.occurred_on}</td><td>{m.movement_type}</td><td>{products.data?.find(p => p.id === m.product_id)?.name ?? m.product_id}</td><td>{m.quantity}</td><td>{pkr(m.unit_cost)}</td><td>{m.reference_type ?? "—"}</td></tr>)}</tbody></table>{!movements.isPending && !movements.data?.length && <p className="empty">No stock movements yet.</p>}</section></section>;
}

function ProductCreatePanel() {
  const client = useQueryClient();
  const [sku, setSku] = useState("");
  const [name, setName] = useState("");
  const [packaging, setPackaging] = useState("Dabba");
  const [cost, setCost] = useState("");
  const [selling, setSelling] = useState("");
  const [minimum, setMinimum] = useState("0");
  const [opening, setOpening] = useState("0");
  const [tokenEnabled, setTokenEnabled] = useState(false);
  const [tokenValue, setTokenValue] = useState("0");
  const create = useMutation({ mutationFn: async () => { if (tokenEnabled && Number(tokenValue) <= 0) throw new Error("Enter a token value when Token bearing is enabled."); const product = await request<Product>("/products", { method: "POST", body: JSON.stringify({ sku, name, packaging, cost_price: Number(cost || 0), selling_price: Number(selling || 0), minimum_stock: Number(minimum || 0), token_enabled: tokenEnabled, token_value: tokenEnabled ? Number(tokenValue || 0) : 0 }) }); if (Number(opening) > 0) await request("/inventory/adjustments", { method: "POST", body: JSON.stringify({ product_id: product.id, quantity: Number(opening), unit_cost: Number(cost || 0), notes: "Opening stock" }) }); return product; }, onSuccess: () => { setSku(""); setName(""); setPackaging("Dabba"); setCost(""); setSelling(""); setMinimum("0"); setOpening("0"); setTokenEnabled(false); setTokenValue("0"); client.invalidateQueries({ queryKey: ["products"] }); client.invalidateQueries({ queryKey: ["stock"] }); } });
  return <><section className="panel"><h2>Add product package</h2><p className="hint">Create Dabba, Gallon, and Drum separately for the same paint. Each package has its own SKU, price, opening stock, and token setting.</p><form className="line-adder" onSubmit={event => { event.preventDefault(); create.mutate(); }}><input required aria-label="SKU" placeholder="SKU, e.g. EMUL-DB" value={sku} onChange={e => setSku(e.target.value)} /><input required aria-label="Product name" placeholder="Paint name" value={name} onChange={e => setName(e.target.value)} /><select aria-label="Packaging" value={packaging} onChange={e => setPackaging(e.target.value)}><option value="Dabba">Dabba</option><option value="Gallon">Gallon</option><option value="Drum">Drum</option><option value="Other">Other</option></select><input required aria-label="Cost price" type="number" min="0" step="0.01" placeholder="Cost price" value={cost} onChange={e => setCost(e.target.value)} /><input required aria-label="Selling price" type="number" min="0" step="0.01" placeholder="Selling price" value={selling} onChange={e => setSelling(e.target.value)} /><input required aria-label="Minimum stock alert" type="number" min="0" step="0.001" placeholder="Minimum stock alert" value={minimum} onChange={e => setMinimum(e.target.value)} /><input required aria-label="Opening quantity" type="number" min="0" step="0.001" placeholder="Opening quantity" value={opening} onChange={e => setOpening(e.target.value)} /><label className="inline"><input type="checkbox" checked={tokenEnabled} onChange={e => { setTokenEnabled(e.target.checked); if (!e.target.checked) setTokenValue("0"); }} /> Token bearing</label>{tokenEnabled && <input required aria-label="Token value" type="number" min="0.01" step="0.01" placeholder="Token value (PKR)" value={tokenValue} onChange={e => setTokenValue(e.target.value)} />}<button disabled={create.isPending}>{create.isPending ? "Saving…" : "Save package"}</button></form>{create.error && <p className="error">{create.error.message}</p>}</section><ProductEditPanel /></>;
}

function ProductEditPanel() {
  const client = useQueryClient();
  const products = useQuery({ queryKey: ["products"], queryFn: () => request<ProductPlus[]>("/products?limit=200") });
  const [id, setId] = useState("");
  const [form, setForm] = useState<ProductPlus | null>(null);
  const save = useMutation({ mutationFn: () => request(`/products/${id}`, { method: "PUT", body: JSON.stringify({ ...form, cost_price: Number(form?.cost_price || 0), selling_price: Number(form?.selling_price || 0), minimum_stock: Number(form?.minimum_stock || 0), token_enabled: Boolean(form?.token_enabled), token_value: form?.token_enabled ? Number(form?.token_value || 0) : 0 }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["products"] }); client.invalidateQueries({ queryKey: ["stock"] }); } });
  const select = (productId: string) => { setId(productId); const product = products.data?.find(item => item.id === productId); setForm(product ? { ...product } : null); };
  return <section className="panel"><h2>Edit saved product</h2><p className="hint">Token bearing and token value can be changed here. Change quantities through Stock adjustment so the stock history remains accurate.</p><select value={id} onChange={e => select(e.target.value)}><option value="">Choose a product package</option>{products.data?.map(product => <option key={product.id} value={product.id}>{product.sku} — {product.name} ({product.packaging})</option>)}</select>{form && <form className="line-adder" onSubmit={e => { e.preventDefault(); if (form.token_enabled && Number(form.token_value || 0) <= 0) return; save.mutate(); }}><input required value={form.sku} onChange={e => setForm({ ...form, sku: e.target.value })} /><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><select value={form.packaging} onChange={e => setForm({ ...form, packaging: e.target.value as ProductPlus["packaging"] })}><option>Dabba</option><option>Gallon</option><option>Drum</option><option>Other</option></select><input required type="number" min="0" step="0.01" value={form.cost_price} onChange={e => setForm({ ...form, cost_price: e.target.value })} /><input required type="number" min="0" step="0.01" value={form.selling_price} onChange={e => setForm({ ...form, selling_price: e.target.value })} /><input required type="number" min="0" step="0.001" value={form.minimum_stock} onChange={e => setForm({ ...form, minimum_stock: Number(e.target.value) })} /><label className="inline"><input type="checkbox" checked={Boolean(form.token_enabled)} onChange={e => setForm({ ...form, token_enabled: e.target.checked, token_value: e.target.checked ? form.token_value : "0" })} /> Token bearing</label>{form.token_enabled && <input required type="number" min="0.01" step="0.01" aria-label="Token value" placeholder="Token value (PKR)" value={form.token_value ?? "0"} onChange={e => setForm({ ...form, token_value: e.target.value })} />}<button disabled={save.isPending}>{save.isPending ? "Saving…" : "Save changes"}</button></form>}{save.error && <p className="error">{save.error.message}</p>}{save.isSuccess && <p className="success">Product details updated. Stock quantity was not changed.</p>}</section>;
}
