import { FormEvent, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { InvoiceLine, InvoiceResult, Party, Product, request } from "./api";

type Kind = "sale" | "purchase";
const money = (value: number) => new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR" }).format(value);

export function InvoiceEntry({ kind }: { kind: Kind }) {
  const isSale = kind === "sale"; const partyLabel = isSale ? "Customer" : "Supplier";
  const [partyId, setPartyId] = useState(""); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState(1); const [price, setPrice] = useState(0); const [paidAmount, setPaidAmount] = useState(0); const [lines, setLines] = useState<InvoiceLine[]>([]); const [notice, setNotice] = useState<string | null>(null);
  const products = useQuery({ queryKey: ["products"], queryFn: () => request<Product[]>("/products?limit=200") });
  const parties = useQuery({ queryKey: [isSale ? "customers" : "suppliers"], queryFn: () => request<Party[]>(isSale ? "/customers?limit=200" : "/suppliers?limit=200") });
  const total = useMemo(() => lines.reduce((sum, line) => sum + line.quantity * line.unit_price - line.discount_amount, 0), [lines]);
  const mutation = useMutation({ mutationFn: () => request<InvoiceResult>(isSale ? "/sales" : "/purchases", { method: "POST", body: JSON.stringify({ [isSale ? "customer_id" : "supplier_id"]: partyId, paid_amount: paidAmount, payment_method: "cash", items: lines }) }), onSuccess: invoice => { setNotice(`${isSale ? "Sale" : "Purchase"} ${invoice.invoice_number} posted. Total: ${invoice.grand_total}; due: ${invoice.due_amount}.`); setLines([]); setPaidAmount(0); }, onError: error => setNotice(error.message) });
  const selectProduct = (id: string) => { setProductId(id); const product = products.data?.find(item => item.id === id); if (product) setPrice(Number(isSale ? product.selling_price : product.cost_price)); };
  const addLine = () => { if (!productId || quantity <= 0 || price < 0) return; setLines(current => [...current, { product_id: productId, quantity, unit_price: price, discount_amount: 0 }]); setProductId(""); setQuantity(1); setPrice(0); };
  const submit = (event: FormEvent) => { event.preventDefault(); setNotice(null); if (!partyId || !lines.length) { setNotice(`Select a ${partyLabel.toLowerCase()} and add at least one item.`); return; } mutation.mutate(); };
  return <section className="invoice-page"><p className="eyebrow">{isSale ? "SALES" : "PURCHASES"}</p><h1>New {isSale ? "sales" : "purchase"} invoice</h1><form onSubmit={submit}><div className="invoice-grid"><section className="panel"><label>{partyLabel}<select required value={partyId} onChange={e => setPartyId(e.target.value)}><option value="">Select {partyLabel.toLowerCase()}</option>{parties.data?.map(party => <option key={party.id} value={party.id}>{party.name}</option>)}</select></label><label>Payment now (PKR)<input type="number" min="0" step="0.01" value={paidAmount} onChange={e => setPaidAmount(Number(e.target.value))} /></label><p className="hint">The remainder posts automatically to {isSale ? "receivables" : "payables"}.</p></section><section className="panel"><h2>Add product</h2><div className="line-adder"><select value={productId} onChange={e => selectProduct(e.target.value)}><option value="">Select product</option>{products.data?.map(product => <option key={product.id} value={product.id}>{product.sku} — {product.name}</option>)}</select><input aria-label="Quantity" type="number" min="0.001" step="0.001" value={quantity} onChange={e => setQuantity(Number(e.target.value))} /><input aria-label="Unit price" type="number" min="0" step="0.01" value={price} onChange={e => setPrice(Number(e.target.value))} /><button type="button" onClick={addLine}>Add</button></div></section></div><section className="panel"><h2>Invoice items</h2>{lines.length === 0 ? <p className="empty">No items yet.</p> : <table><thead><tr><th>Product</th><th>Qty</th><th>Price</th><th>Total</th><th /></tr></thead><tbody>{lines.map((line, index) => { const product = products.data?.find(item => item.id === line.product_id); return <tr key={`${line.product_id}-${index}`}><td>{product?.name ?? line.product_id}</td><td>{line.quantity}</td><td>{money(line.unit_price)}</td><td>{money(line.quantity * line.unit_price)}</td><td><button type="button" className="text-button" onClick={() => setLines(current => current.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></td></tr>; })}</tbody></table>}<div className="invoice-total"><span>Pre-tax total</span><strong>{money(total)}</strong></div><p className="hint">The backend applies the configured product tax rates and posts the ledger entries.</p><button disabled={mutation.isPending || !lines.length}>{mutation.isPending ? "Posting…" : `Post ${isSale ? "sale" : "purchase"}`}</button>{notice && <p className={mutation.isError ? "error" : "success"}>{notice}</p>}</section></form></section>;
}
