import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Product, request, User } from "./api";

type Dashboard = { sales_today: string; sales_month: string; purchases_month: string; inventory_value: string; cash_balance: string; bank_balance: string; receivables: string; payables: string; gross_profit: string; net_profit: string; low_stock: { name: string; quantity: string }[] };
type Stock = { product_id: string; sku: string; name: string; packaging: string; quantity: string; value: string; minimum_stock: string; is_low_stock: boolean };
type Movement = { id: string; product_id: string; movement_type: string; quantity: string; unit_cost: string; occurred_on: string; reference_type?: string; notes?: string };
type Business = { business_name: string; address?: string; phone?: string; email?: string; tax_number?: string; invoice_prefix: string; show_tax_on_invoice: boolean };
const pkr = (value: string | number) => new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", maximumFractionDigits: 0 }).format(Number(value));

export function DashboardView() {
  const report = useQuery({ queryKey: ["dashboard"], queryFn: () => request<Dashboard>("/reports/dashboard") });
  if (report.isPending) return <p>Loading dashboard…</p>; if (report.error || !report.data) return <p className="error">{report.error?.message ?? "Dashboard could not be loaded."}</p>;
  const item = report.data;
  return <><section className="cards">{[["Today’s sales", item.sales_today], ["Monthly sales", item.sales_month], ["Monthly purchases", item.purchases_month], ["Inventory value", item.inventory_value], ["Receivables", item.receivables], ["Payables", item.payables], ["Gross profit", item.gross_profit], ["Net profit", item.net_profit]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{pkr(value)}</strong></article>)}</section><section className="panel"><h2>Low-stock products</h2>{item.low_stock.length ? <ul>{item.low_stock.map(product => <li key={product.name}>{product.name}: {product.quantity}</li>)}</ul> : <p className="success">No low-stock products.</p>}</section></>;
}

export function InventoryView() {
  const client = useQueryClient(); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState(0); const [notes, setNotes] = useState("");
  const stock = useQuery({ queryKey: ["stock"], queryFn: () => request<Stock[]>("/inventory/stock") }); const products = useQuery({ queryKey: ["products"], queryFn: () => request<Product[]>("/products?limit=200") }); const movements = useQuery({ queryKey: ["stock-movements"], queryFn: () => request<Movement[]>("/inventory/movements?limit=200") });
  const adjustment = useMutation({ mutationFn: () => request("/inventory/adjustments", { method: "POST", body: JSON.stringify({ product_id: productId, quantity, notes }) }), onSuccess: () => { setProductId(""); setQuantity(0); setNotes(""); client.invalidateQueries({ queryKey: ["stock"] }); client.invalidateQueries({ queryKey: ["stock-movements"] }); } });
  const submit = (event: FormEvent) => { event.preventDefault(); adjustment.mutate(); };
  return <section className="invoice-page"><h1>Inventory</h1><ProductCreatePanel /><section className="panel"><h2>Stock adjustment</h2><form className="line-adder" onSubmit={submit}><select required value={productId} onChange={e => setProductId(e.target.value)}><option value="">Select product</option>{products.data?.map(product => <option key={product.id} value={product.id}>{product.sku} — {product.name}</option>)}</select><input required type="number" step="0.001" placeholder="+/- quantity" value={quantity || ""} onChange={e => setQuantity(Number(e.target.value))} /><input required placeholder="Reason / notes" value={notes} onChange={e => setNotes(e.target.value)} /><button disabled={adjustment.isPending}>Post adjustment</button></form>{adjustment.error && <p className="error">{adjustment.error.message}</p>}</section><section className="panel"><h2>Current stock</h2><table><thead><tr><th>SKU</th><th>Product</th><th>Quantity</th><th>Value</th><th>Status</th></tr></thead><tbody>{stock.data?.map(item => <tr key={item.product_id}><td>{item.sku}</td><td>{item.name}</td><td>{item.quantity}</td><td>{pkr(item.value)}</td><td>{item.is_low_stock ? "Low stock" : "OK"}</td></tr>)}</tbody></table></section><section className="panel"><h2>Movement history</h2><table><thead><tr><th>Date</th><th>Type</th><th>Product</th><th>Quantity</th><th>Unit cost</th><th>Reference</th></tr></thead><tbody>{movements.data?.map(m => <tr key={m.id}><td>{m.occurred_on}</td><td>{m.movement_type}</td><td>{products.data?.find(p => p.id === m.product_id)?.name ?? m.product_id}</td><td>{m.quantity}</td><td>{pkr(m.unit_cost)}</td><td>{m.reference_type ?? "—"}</td></tr>)}</tbody></table>{!movements.isPending && !movements.data?.length && <p className="empty">No stock movements yet.</p>}</section></section>;
}

function ProductCreatePanel() {
  const client = useQueryClient(); const [sku, setSku] = useState(""); const [name, setName] = useState(""); const [packaging, setPackaging] = useState("Dabba"); const [cost, setCost] = useState(""); const [selling, setSelling] = useState(""); const [minimum, setMinimum] = useState("0"); const [opening, setOpening] = useState("0");
  const create = useMutation({ mutationFn: async () => { const product = await request<Product>("/products", { method: "POST", body: JSON.stringify({ sku, name, packaging, cost_price: Number(cost || 0), selling_price: Number(selling || 0), minimum_stock: Number(minimum || 0) }) }); if (Number(opening) > 0) await request("/inventory/adjustments", { method: "POST", body: JSON.stringify({ product_id: product.id, quantity: Number(opening), unit_cost: Number(cost || 0), notes: "Opening stock" }) }); return product; }, onSuccess: () => { setSku(""); setName(""); setPackaging("Dabba"); setCost(""); setSelling(""); setMinimum("0"); setOpening("0"); client.invalidateQueries({ queryKey: ["products"] }); client.invalidateQueries({ queryKey: ["stock"] }); } });
  return <section className="panel"><h2>Add product package</h2><p className="hint">Create Dabba, Gallon, and Drum separately for the same paint. Each package has its own SKU, price, opening stock, and future movements.</p><form className="line-adder" onSubmit={event => { event.preventDefault(); create.mutate(); }}><input required aria-label="SKU" placeholder="SKU, e.g. EMUL-DB" value={sku} onChange={e => setSku(e.target.value)} /><input required aria-label="Product name" placeholder="Paint name" value={name} onChange={e => setName(e.target.value)} /><select aria-label="Packaging" value={packaging} onChange={e => setPackaging(e.target.value)}><option value="Dabba">Dabba</option><option value="Gallon">Gallon</option><option value="Drum">Drum</option></select><input required aria-label="Cost price" type="number" min="0" step="0.01" placeholder="Cost price" value={cost} onChange={e => setCost(e.target.value)} /><input required aria-label="Selling price" type="number" min="0" step="0.01" placeholder="Selling price" value={selling} onChange={e => setSelling(e.target.value)} /><input required aria-label="Minimum stock alert" type="number" min="0" step="0.001" placeholder="Minimum stock alert" value={minimum} onChange={e => setMinimum(e.target.value)} /><input required aria-label="Opening quantity" type="number" min="0" step="0.001" placeholder="Opening quantity" value={opening} onChange={e => setOpening(e.target.value)} /><button disabled={create.isPending}>{create.isPending ? "Saving…" : "Save package"}</button></form>{create.error && <p className="error">{create.error.message}</p>}</section>;
}

export function SettingsView() {
  const client = useQueryClient(); const business = useQuery({ queryKey: ["business"], queryFn: () => request<Business>("/settings/business") }); const users = useQuery({ queryKey: ["users"], queryFn: () => request<User[]>("/users") });
  const [form, setForm] = useState<Business | null>(null); const [email, setEmail] = useState(""); const [fullName, setFullName] = useState(""); const [password, setPassword] = useState("");
  const save = useMutation({ mutationFn: () => request<Business>("/settings/business", { method: "PUT", body: JSON.stringify(form) }), onSuccess: data => { setForm(data); client.invalidateQueries({ queryKey: ["business"] }); } });
  const addUser = useMutation({ mutationFn: () => request<User>("/users", { method: "POST", body: JSON.stringify({ email, full_name: fullName, password, role: "salesperson" }) }), onSuccess: () => { setEmail(""); setFullName(""); setPassword(""); client.invalidateQueries({ queryKey: ["users"] }); } });
  const values = form ?? business.data;
  if (!values) return <p>Loading settings…</p>;
  return <section className="invoice-page"><h1>Settings & users</h1><section className="panel"><h2>Business information</h2><form className="settings-form" onSubmit={e => { e.preventDefault(); save.mutate(); }}><input value={values.business_name} placeholder="Business name" onChange={e => setForm({ ...values, business_name: e.target.value })} /><input value={values.phone ?? ""} placeholder="Phone" onChange={e => setForm({ ...values, phone: e.target.value })} /><input value={values.email ?? ""} placeholder="Email" onChange={e => setForm({ ...values, email: e.target.value })} /><input value={values.tax_number ?? ""} placeholder="NTN / tax number" onChange={e => setForm({ ...values, tax_number: e.target.value })} /><input value={values.address ?? ""} placeholder="Address" onChange={e => setForm({ ...values, address: e.target.value })} /><button disabled={save.isPending}>Save business settings</button></form></section><section className="panel"><h2>Users</h2><form className="line-adder" onSubmit={e => { e.preventDefault(); addUser.mutate(); }}><input required placeholder="Full name" value={fullName} onChange={e => setFullName(e.target.value)} /><input required type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} /><input required type="password" minLength={8} placeholder="Temporary password" value={password} onChange={e => setPassword(e.target.value)} /><button>Add user</button></form><ul>{users.data?.map(user => <li key={user.id}>{user.full_name} — {user.role} ({user.is_active ? "active" : "inactive"})</li>)}</ul></section></section>;
}

type Account = { id: string; code: string; name: string; type: string; active: boolean };
export function FinanceView() {
  const accounts = useQuery({ queryKey: ["accounts"], queryFn: () => request<Account[]>("/reports/accounts") }); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [expenseAccount, setExpenseAccount] = useState(""); const [cashAccount, setCashAccount] = useState(""); const [transactionType, setTransactionType] = useState("transfer"); const [offsetAccount, setOffsetAccount] = useState("");
  const expense = useMutation({ mutationFn: () => request("/reports/expenses", { method: "POST", body: JSON.stringify({ description, amount: Number(amount), expense_account_id: expenseAccount, cash_bank_account_id: cashAccount }) }), onSuccess: () => { setDescription(""); setAmount(""); } });
  const cash = useMutation({ mutationFn: () => request("/reports/cash-bank-transactions", { method: "POST", body: JSON.stringify({ transaction_type: transactionType, amount: Number(amount), account_id: cashAccount, offset_account_id: offsetAccount, description }) }), onSuccess: () => { setDescription(""); setAmount(""); } });
  const submitExpense = (event: FormEvent) => { event.preventDefault(); expense.mutate(); }; const submitCash = (event: FormEvent) => { event.preventDefault(); cash.mutate(); };
  return <section className="invoice-page"><h1>Expenses & cash/bank</h1><div className="invoice-grid"><section className="panel"><h2>Post expense</h2><form className="settings-form" onSubmit={submitExpense}><input required placeholder="Description" value={description} onChange={e => setDescription(e.target.value)} /><input required min="0.01" type="number" step="0.01" placeholder="Amount" value={amount} onChange={e => setAmount(e.target.value)} /><select required value={expenseAccount} onChange={e => setExpenseAccount(e.target.value)}><option value="">Expense account</option>{accounts.data?.filter(account => account.type === "expense").map(account => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select><select required value={cashAccount} onChange={e => setCashAccount(e.target.value)}><option value="">Paid from</option>{accounts.data?.filter(account => account.code === "1000" || account.code === "1010").map(account => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select><button disabled={expense.isPending}>Post expense</button></form>{expense.error && <p className="error">{expense.error.message}</p>}{expense.isSuccess && <p className="success">Expense posted to the general ledger.</p>}</section><section className="panel"><h2>Cash / bank transaction</h2><form className="settings-form" onSubmit={submitCash}><select value={transactionType} onChange={e => setTransactionType(e.target.value)}><option value="transfer">Transfer</option><option value="receipt">Receipt</option><option value="payment">Payment</option></select><input required min="0.01" type="number" step="0.01" placeholder="Amount" value={amount} onChange={e => setAmount(e.target.value)} /><select required value={cashAccount} onChange={e => setCashAccount(e.target.value)}><option value="">Cash/bank account</option>{accounts.data?.filter(account => account.code === "1000" || account.code === "1010").map(account => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select><select required value={offsetAccount} onChange={e => setOffsetAccount(e.target.value)}><option value="">Offset account</option>{accounts.data?.map(account => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select><input required placeholder="Description" value={description} onChange={e => setDescription(e.target.value)} /><button disabled={cash.isPending}>Post transaction</button></form>{cash.error && <p className="error">{cash.error.message}</p>}{cash.isSuccess && <p className="success">Cash/bank transaction posted.</p>}</section></div></section>;
}
