import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { downloadPdf, Party, request } from "./api";

type Invoice = { id: string; invoice_number: string; invoice_date: string; customer_id?: string; supplier_id?: string; grand_total: string; paid_amount: string; due_amount: string; status: string; items: { id: string; product_id: string; description: string; quantity: string }[] };
type Ledger = { entries: { date: string; reference: string; type: string; debit: string | number; credit: string | number; balance?: string | number }[]; outstanding: string | number };
const pkr = (value: string | number) => new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", maximumFractionDigits: 0 }).format(Number(value));

export function InvoiceHistoryView({ kind }: { kind: "sale" | "purchase" }) {
  const path = kind === "sale" ? "/sales" : "/purchases"; const pdfPath = kind === "sale" ? "/reports/sales" : "/reports/purchases"; const [search, setSearch] = useState(""); const [submitted, setSubmitted] = useState("");
  const invoices = useQuery({ queryKey: [path, submitted], queryFn: () => request<Invoice[]>(`${path}?limit=200${submitted ? `&q=${encodeURIComponent(submitted)}` : ""}`) });
  return <section className="invoice-page"><h1>{kind === "sale" ? "Sales" : "Purchases"} history</h1><section className="panel inline"><input placeholder="Search invoice number" value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => { if (e.key === "Enter") setSubmitted(search); }} /><button type="button" onClick={() => setSubmitted(search)}>Search</button></section><section className="panel"><table><thead><tr><th>Invoice</th><th>Date</th><th>Total</th><th>Paid</th><th>Due</th><th>Status</th><th /></tr></thead><tbody>{invoices.data?.map(invoice => <tr key={invoice.id}><td>{invoice.invoice_number}</td><td>{invoice.invoice_date}</td><td>{pkr(invoice.grand_total)}</td><td>{pkr(invoice.paid_amount)}</td><td>{pkr(invoice.due_amount)}</td><td>{invoice.status}</td><td><button type="button" className="text-button" onClick={() => downloadPdf(`${pdfPath}/${invoice.id}/pdf`, `${invoice.invoice_number}.pdf`)}>PDF</button></td></tr>)}</tbody></table>{!invoices.isPending && !invoices.data?.length && <p className="empty">No invoices found.</p>}</section></section>;
}

export function PaymentView({ kind }: { kind: "customer" | "supplier" }) {
  const isCustomer = kind === "customer"; const client = useQueryClient(); const [partyId, setPartyId] = useState(""); const [invoiceId, setInvoiceId] = useState(""); const [amount, setAmount] = useState("");
  const parties = useQuery({ queryKey: [kind + "-parties"], queryFn: () => request<Party[]>(isCustomer ? "/customers?limit=200" : "/suppliers?limit=200") }); const invoices = useQuery({ queryKey: [kind + "-open-invoices"], queryFn: () => request<Invoice[]>(isCustomer ? "/sales?limit=200" : "/purchases?limit=200") });
  const open = invoices.data?.filter(invoice => Number(invoice.due_amount) > 0 && (isCustomer ? invoice.customer_id === partyId : invoice.supplier_id === partyId)) ?? [];
  const mutation = useMutation({ mutationFn: () => request(isCustomer ? "/sales/payments" : "/purchases/payments", { method: "POST", body: JSON.stringify({ [isCustomer ? "customer_id" : "supplier_id"]: partyId, amount: Number(amount), method: "cash", allocations: [{ invoice_id: invoiceId, amount: Number(amount) }] }) }), onSuccess: () => { setAmount(""); setInvoiceId(""); client.invalidateQueries({ queryKey: [kind + "-open-invoices"] }); } });
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate(); };
  return <section className="invoice-page"><h1>{isCustomer ? "Receive customer payment" : "Pay supplier"}</h1><section className="panel"><form className="settings-form" onSubmit={submit}><select required value={partyId} onChange={e => setPartyId(e.target.value)}><option value="">Select {isCustomer ? "customer" : "supplier"}</option>{parties.data?.map(party => <option key={party.id} value={party.id}>{party.name}</option>)}</select><select required value={invoiceId} onChange={e => setInvoiceId(e.target.value)}><option value="">Select open invoice</option>{open.map(invoice => <option key={invoice.id} value={invoice.id}>{invoice.invoice_number} — due {pkr(invoice.due_amount)}</option>)}</select><input required min="0.01" type="number" step="0.01" placeholder="Amount" value={amount} onChange={e => setAmount(e.target.value)} /><button disabled={mutation.isPending}>Post payment</button></form>{mutation.error && <p className="error">{mutation.error.message}</p>}{mutation.isSuccess && <p className="success">Payment posted and allocated.</p>}</section></section>;
}

export function LedgerView({ kind }: { kind: "customer" | "supplier" }) {
  const isCustomer = kind === "customer"; const [partyId, setPartyId] = useState(""); const parties = useQuery({ queryKey: [kind + "-ledger-parties"], queryFn: () => request<Party[]>(isCustomer ? "/customers?limit=200" : "/suppliers?limit=200") }); const ledger = useQuery({ queryKey: [kind + "-ledger", partyId], queryFn: () => request<Ledger>(`/reports/${isCustomer ? "customers" : "suppliers"}/${partyId}/ledger`), enabled: Boolean(partyId) });
  return <section className="invoice-page"><h1>{isCustomer ? "Customer" : "Supplier"} ledger</h1><section className="panel"><select value={partyId} onChange={e => setPartyId(e.target.value)}><option value="">Select {isCustomer ? "customer" : "supplier"}</option>{parties.data?.map(party => <option key={party.id} value={party.id}>{party.name}</option>)}</select></section>{ledger.data && <section className="panel"><h2>Outstanding: {pkr(ledger.data.outstanding)}</h2><table><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{ledger.data.entries.map(entry => <tr key={`${entry.reference}-${entry.date}`}><td>{entry.date}</td><td>{entry.reference}</td><td>{entry.type}</td><td>{pkr(entry.debit)}</td><td>{pkr(entry.credit)}</td></tr>)}</tbody></table></section>}</section>;
}

export function ReportsView() {
  const report = useQuery({ queryKey: ["trial-balance"], queryFn: () => request<{ code: string; name: string; type: string; debit: string; credit: string; balance: string }[]>("/reports/trial-balance") });
  return <section className="invoice-page"><h1>Trial balance</h1><section className="panel"><table><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{report.data?.map(row => <tr key={row.code}><td>{row.code}</td><td>{row.name}</td><td>{row.type}</td><td>{pkr(row.debit)}</td><td>{pkr(row.credit)}</td><td>{pkr(row.balance)}</td></tr>)}</tbody></table></section></section>;
}

export function PartiesView({ kind }: { kind: "customer" | "supplier" }) {
  const isCustomer = kind === "customer"; const client = useQueryClient(); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [address, setAddress] = useState(""); const [creditLimit, setCreditLimit] = useState("0");
  const path = isCustomer ? "/customers" : "/suppliers"; const parties = useQuery({ queryKey: [kind + "-master"], queryFn: () => request<Party[]>(`${path}?limit=200`) });
  const create = useMutation({ mutationFn: () => request<Party>(path, { method: "POST", body: JSON.stringify({ name, phone, address, ...(isCustomer ? { credit_limit: Number(creditLimit) } : {}) }) }), onSuccess: () => { setName(""); setPhone(""); setAddress(""); setCreditLimit("0"); client.invalidateQueries({ queryKey: [kind + "-master"] }); client.invalidateQueries({ queryKey: [isCustomer ? "customers" : "suppliers"] }); } });
  return <section className="invoice-page"><h1>{isCustomer ? "Customers" : "Suppliers"}</h1><section className="panel"><h2>Add {isCustomer ? "customer" : "supplier"}</h2><form className="settings-form" onSubmit={event => { event.preventDefault(); create.mutate(); }}><input required placeholder="Name" value={name} onChange={e => setName(e.target.value)} /><input placeholder="Phone" value={phone} onChange={e => setPhone(e.target.value)} /><input placeholder="Address" value={address} onChange={e => setAddress(e.target.value)} />{isCustomer && <input type="number" min="0" step="0.01" placeholder="Credit limit" value={creditLimit} onChange={e => setCreditLimit(e.target.value)} />}<button disabled={create.isPending}>Save {isCustomer ? "customer" : "supplier"}</button></form>{create.error && <p className="error">{create.error.message}</p>}{create.isSuccess && <p className="success">Saved successfully.</p>}</section><section className="panel"><h2>Saved {isCustomer ? "customers" : "suppliers"}</h2><ul>{parties.data?.map(party => <li key={party.id}>{party.name}</li>)}</ul></section></section>;
}

export function ReturnView({ kind }: { kind: "sale" | "purchase" }) {
  const isSale = kind === "sale"; const client = useQueryClient(); const [invoiceId, setInvoiceId] = useState(""); const [lineId, setLineId] = useState(""); const [quantity, setQuantity] = useState(1);
  const invoices = useQuery({ queryKey: [kind + "-return-invoices"], queryFn: () => request<Invoice[]>(`${isSale ? "/sales" : "/purchases"}?limit=200`) }); const invoice = invoices.data?.find(item => item.id === invoiceId);
  const mutation = useMutation({ mutationFn: () => request(`${isSale ? "/sales" : "/purchases"}/${invoiceId}/returns`, { method: "POST", body: JSON.stringify({ items: [{ source_line_id: lineId, quantity }] }) }), onSuccess: () => { setInvoiceId(""); setLineId(""); setQuantity(1); client.invalidateQueries({ queryKey: [kind + "-return-invoices"] }); } });
  return <section className="invoice-page"><h1>{isSale ? "Sales return" : "Purchase return"}</h1><section className="panel"><form className="settings-form" onSubmit={event => { event.preventDefault(); mutation.mutate(); }}><select required value={invoiceId} onChange={e => { setInvoiceId(e.target.value); setLineId(""); }}><option value="">Select posted invoice</option>{invoices.data?.filter(item => item.status === "posted").map(item => <option key={item.id} value={item.id}>{item.invoice_number} — {pkr(item.grand_total)}</option>)}</select><select required value={lineId} onChange={e => setLineId(e.target.value)}><option value="">Select item to return</option>{invoice?.items.map((item, index) => <option key={item.product_id + index} value={item.id}>{item.description} — quantity {item.quantity}</option>)}</select><input required min="0.001" step="0.001" type="number" value={quantity} onChange={e => setQuantity(Number(e.target.value))} /><button disabled={mutation.isPending}>Post return</button></form>{mutation.error && <p className="error">{mutation.error.message}</p>}{mutation.isSuccess && <p className="success">Return posted and inventory/accounting updated.</p>}</section></section>;
}
